# This is a basic workflow to help you get started with Actions

name: Build and Deploy Helm Chart Sonarqube

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        required: true
        default: 'development'
        type: choice
        options:
          - development
          - staging
          - production

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  deploy-development:
    if: github.event.inputs.environment == 'development'
    runs-on: ubuntu-latest
    env:
      AWS_REGION: ${ secrets.AWS_REGION }
      AWS_ROLE_TO_ASSUME: ${ secrets.AWS_ROLE_TO_ASSUME }
      EKS_CLUSTER_NAME: ${ secrets.EKS_CLUSTER_NAME }
      POSTGRESQL_PASSWORD: ${ secrets.POSTGRESQL_PASSWORD }
      POSTGRESQL_USERNAME: ${ secrets.POSTGRESQL_USERNAME }
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
      # Runs a single command using the runners shell
      - name: Assume AWS Role and Deploy to EKS
        run:

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
